### ISSUE TITLE
IRC SSL

### ISSUE THREAD

**Issue by Sorunome** [Sorunome/OmnomIRC2#21]
Allow the IRC bot to use SSL

**Comment by Sorunome** [comment]
done with https://github.com/Sorunome/OmnomIRC2/commit/a4e90ecb971f0fabc74d9b477a8009f0210e6f27

**Comment by DJOmnimaga** [comment]
Major bug since version 2.9 upgrade last night: Every single site staff lost admin access to OmnomIRC. After investigation by Streetwalrus, the Omnom database indicates otherwise (4 groups are listed). Yet, no one (not even the root SMF admin group) can access Omnom admin panel anymore.

**Comment by Sorunome** [comment]
please open a new issue instead of commenting on a random old one

**Comment by Sorunome** [comment]
Anyways, fixed with https://github.com/Sorunome/OmnomIRC2/commit/4570e1c057ab359d974a8855029b7e44f4dc2020

**Comment by DJOmnimaga** [comment]
How do I do that?

**Comment by Sorunome** [comment]
on https://github.com/Sorunome/OmnomIRC2/issues is in the top-right corner a big 'new issue' button
