### ISSUE TITLE
Add indexes for performance

### ISSUE THREAD

**Issue by Eeems** [Sorunome/OmnomIRC2#27]
Due to the frequency of queries that search based on these columns, indexes should be added.
 * irc_lines.type
 * irc_users.isOnline
 * irc_users.channel
 * irc_users.username
 * irc_users.online

FYI - I've already indexed these columns on Omnimaga

**Comment by Sorunome** [comment]
Fixed with https://github.com/Sorunome/OmnomIRC2/commit/e6e246093c86f7b346ac9be513ff0d19aaa939eb
