### ISSUE TITLE
Add Greentext

### ISSUE THREAD

**Issue by pcbmaster** [Sorunome/OmnomIRC2#35]
>2015
>not supporting greentext
come on

**Comment by Eeems** [comment]
I'm a little confused as to what you mean by greentext. Do you mean adding the ability to change the colour of the text/background?

**Comment by Sorunome** [comment]
that >blah appears green

**Comment by Eeems** [comment]
Why would you want add that to an IRC client?

**Comment by Sorunome** [comment]
because >greentext is awesome

**Comment by Eeems** [comment]
But not part of IRC.

**Comment by Sorunome** [comment]
No i thought i'd make it so that if you enable and the message starts with > it'll prepend the irc color codes for green to your message before sending to the server, thus all client-sided

**Comment by Eeems** [comment]
If you add support, I'd suggest adding it in a way that it can be disabled per-channel and/or per-network on the admin panel

**Comment by Sorunome** [comment]
the thing is, if i do it that way, it'll look like just any other irc color tag

**Comment by Eeems** [comment]
Yes, you'd be letting users send coloured text to a channel that might not want it. Same with a network that might not want it.

**Comment by pcbmaster** [comment]
Just have omnom color it.  You don't have to actually send the color to IRC.

**Comment by netham45** [comment]
I personally think the idea of an IRC interface supporting greentext is stupid. I feel it would encourage spammy and immature chat.

**Comment by pcbmaster** [comment]
That's just stupid. Just because the text appears green doesn't encourage spam or immature chat.

**Comment by Eeems** [comment]
You don't seem to understand the primary user base of omnomirc. It definitely would encourage it.

**Comment by Sorunome** [comment]
So far nobody abused bold/italics/underline which you can easily add in with the WYSIWYG editor

**Comment by Eeems** [comment]
That's because most people don't know how to use that editor.

**Comment by Sorunome** [comment]
There is a post about that somewhere in the omnomirc thread, lol.
Also, no worries, i'll make it disabled by default.

**Comment by Sorunome** [comment]
Done with https://github.com/Sorunome/OmnomIRC2/commit/c6dfe1e1f5ee66f52eabbe847274a01d24ad5e80
