### ISSUE TITLE
Posted text incorrectly appears across multiple channels client-side

### ISSUE THREAD

**Issue by IJzerbaard** [Sorunome/OmnomIRC2#43]
When OIRC is opened in several tabs and different channels are selected, text posted to one channel also appears (client-side only) in the other channel in the other tab.

For example, here "test" was posted in \#spam in a different tab, but it showed up in the main channel. Client-side only - it's not actually posted to extra channels. Disappears on refresh and channel-change.

![oircbug](https://cloud.githubusercontent.com/assets/12628733/8640079/e1fb7c5a-28eb-11e5-8c96-e8c25487ee7a.png)

**Comment by Sorunome** [comment]
Fixed with https://github.com/Sorunome/OmnomIRC2/commit/0210ae1b9fe0b0d427d16e86d1aa57072f91ed35
