### ISSUE TITLE
Pressing "about" on IDevices couses omnom to infinatly expand east.

### ISSUE THREAD

**Issue by c4ooo** [Sorunome/OmnomIRC2#44]
Pressing about on my ipad couses the page to break formatting/ start to expand east. 
http://i.imgur.com/atOUVUs.jpg
http://i.imgur.com/FKbZeNI.jpg

**Comment by Sorunome** [comment]
fixed in https://github.com/Sorunome/OmnomIRC2/commit/4f9ad744e99cc0f7b50a406c6d74013f36c88172
