### ISSUE TITLE
Cant install it

### ISSUE THREAD

**Issue by muessigb** [Sorunome/OmnomIRC2#45]
When uploading it to my server and browsing to it, it says that its loading. Forever.

**Comment by muessigb** [comment]
So after some investigating I found out that you updated jquery without updating the filename references to the new version.

**Comment by Eeems** [comment]
Repo looks fine. What version did you download?

**Comment by muessigb** [comment]
Latest zip file

**Comment by Eeems** [comment]
@Sorunome looks like you need to upload a new release to fix that.

**Comment by Sorunome** [comment]
Ah i think i fixed this one in the dev version, lemme check.

**Comment by Sorunome** [comment]
Yes, it's fixed in here: https://github.com/Sorunome/OmnomIRC2/commit/ce23031886d60ddabfc6146b5a4b338c96b7f469#diff-f2d77bf1da0ed5bba8372e4e0ffd4563L68

**Comment by Sorunome** [comment]
Fixed with https://github.com/Sorunome/OmnomIRC2/commit/c77b7fd82b83ce899982db498d470f4825ac1d9a
