### ISSUE TITLE
HTML artifacts in new post notifications

### ISSUE THREAD

**Issue by Eeems** [Sorunome/OmnomIRC2#49]
![Screenshot](http://i.imgur.com/0a66VfO.png)

**Comment by Sorunome** [comment]
Aaaah, yeah, forgot to upload the fix for that to omni :P

**Comment by Sorunome** [comment]
yup, fixed in https://github.com/Sorunome/OmnomIRC2/commit/942e511c33a0255176176a4a93166bf0c098c98a
