### ISSUE TITLE
Coloured nicks

### ISSUE THREAD

**Issue by Eeems** [Sorunome/OmnomIRC2#9]
You should colour nicks on IRC and have it configurable per channel.

**Comment by Sorunome** [comment]
I wonder why I didn't do this any sooner.

https://github.com/Sorunome/OmnomIRC2/commit/40eb7e9c14780d5c3b1cc522ae978c96069ec5d1

This is per-network, though.

**Comment by Sorunome** [comment]
Added with https://github.com/Sorunome/OmnomIRC2/commit/b895e052ec9f5e3144cf26cd9318ca43bcb355b3
